default: --format pretty  --format json --out=reportArtifacts/<%= Time.now.strftime("%Y%m%d-%H%M%S") %>-report.json
  --format html --out=reportArtifacts/Report_<%= BROWSER%>.html --tags 'not (@wip or @manual_test)'

landing_page: -p default --tags @landing_page
login: -p default --tags @login
registration: -p default --tags @user_details